# 人教版小学语文写字表 - 看拼音写词语
# 按年级和学期组织，每个词语包含：词语、拼音
# 词语来源于人教版教材写字表要求会写的字组成的词语

WORDS = {
    "一年级上": [
        {"word": "大人", "pinyin": "dà rén"},
        {"word": "大小", "pinyin": "dà xiǎo"},
        {"word": "上下", "pinyin": "shàng xià"},
        {"word": "上山", "pinyin": "shàng shān"},
        {"word": "下山", "pinyin": "xià shān"},
        {"word": "下雨", "pinyin": "xià yǔ"},
        {"word": "天上", "pinyin": "tiān shàng"},
        {"word": "白天", "pinyin": "bái tiān"},
        {"word": "今天", "pinyin": "jīn tiān"},
        {"word": "大地", "pinyin": "dà dì"},
        {"word": "田地", "pinyin": "tián dì"},
        {"word": "土地", "pinyin": "tǔ dì"},
        {"word": "多少", "pinyin": "duō shǎo"},
        {"word": "你好", "pinyin": "nǐ hǎo"},
        {"word": "你们", "pinyin": "nǐ men"},
        {"word": "我们", "pinyin": "wǒ men"},
        {"word": "他们", "pinyin": "tā men"},
        {"word": "人口", "pinyin": "rén kǒu"},
        {"word": "开口", "pinyin": "kāi kǒu"},
        {"word": "耳目", "pinyin": "ěr mù"},
        {"word": "耳朵", "pinyin": "ěr duǒ"},
        {"word": "手心", "pinyin": "shǒu xīn"},
        {"word": "双手", "pinyin": "shuāng shǒu"},
        {"word": "足球", "pinyin": "zú qiú"},
        {"word": "日月", "pinyin": "rì yuè"},
        {"word": "日出", "pinyin": "rì chū"},
        {"word": "月亮", "pinyin": "yuè liang"},
        {"word": "水果", "pinyin": "shuǐ guǒ"},
        {"word": "河水", "pinyin": "hé shuǐ"},
        {"word": "火车", "pinyin": "huǒ chē"},
        {"word": "大火", "pinyin": "dà huǒ"},
        {"word": "山上", "pinyin": "shān shàng"},
        {"word": "火山", "pinyin": "huǒ shān"},
        {"word": "石头", "pinyin": "shí tou"},
        {"word": "水田", "pinyin": "shuǐ tián"},
        {"word": "禾苗", "pinyin": "hé miáo"},
        {"word": "竹子", "pinyin": "zhú zi"},
        {"word": "小马", "pinyin": "xiǎo mǎ"},
        {"word": "马上", "pinyin": "mǎ shàng"},
        {"word": "小鸟", "pinyin": "xiǎo niǎo"},
        {"word": "小鱼", "pinyin": "xiǎo yú"},
        {"word": "金鱼", "pinyin": "jīn yú"},
        {"word": "虫子", "pinyin": "chóng zi"},
        {"word": "白云", "pinyin": "bái yún"},
        {"word": "雨水", "pinyin": "yǔ shuǐ"},
        {"word": "大风", "pinyin": "dà fēng"},
        {"word": "风雨", "pinyin": "fēng yǔ"},
        {"word": "花草", "pinyin": "huā cǎo"},
        {"word": "开花", "pinyin": "kāi huā"},
        {"word": "飞鸟", "pinyin": "fēi niǎo"},
        {"word": "出入", "pinyin": "chū rù"},
        {"word": "出门", "pinyin": "chū mén"},
        {"word": "左右", "pinyin": "zuǒ yòu"},
        {"word": "东西", "pinyin": "dōng xi"},
        {"word": "书本", "pinyin": "shū běn"},
        {"word": "本子", "pinyin": "běn zi"},
        {"word": "正在", "pinyin": "zhèng zài"},
        {"word": "正好", "pinyin": "zhèng hǎo"},
        {"word": "长大", "pinyin": "zhǎng dà"},
        {"word": "回来", "pinyin": "huí lái"},
        {"word": "回家", "pinyin": "huí jiā"},
        {"word": "来去", "pinyin": "lái qù"},
        {"word": "走开", "pinyin": "zǒu kāi"},
        {"word": "开门", "pinyin": "kāi mén"},
        {"word": "关门", "pinyin": "guān mén"},
        {"word": "力气", "pinyin": "lì qi"},
        {"word": "用力", "pinyin": "yòng lì"},
        {"word": "有用", "pinyin": "yǒu yòng"},
    ],

    "一年级下": [
        {"word": "春天", "pinyin": "chūn tiān"},
        {"word": "春风", "pinyin": "chūn fēng"},
        {"word": "冬天", "pinyin": "dōng tiān"},
        {"word": "雪花", "pinyin": "xuě huā"},
        {"word": "下雪", "pinyin": "xià xuě"},
        {"word": "花朵", "pinyin": "huā duǒ"},
        {"word": "草地", "pinyin": "cǎo dì"},
        {"word": "小草", "pinyin": "xiǎo cǎo"},
        {"word": "爷爷", "pinyin": "yé ye"},
        {"word": "奶奶", "pinyin": "nǎi nai"},
        {"word": "爸爸", "pinyin": "bà ba"},
        {"word": "妈妈", "pinyin": "mā ma"},
        {"word": "哥哥", "pinyin": "gē ge"},
        {"word": "姐姐", "pinyin": "jiě jie"},
        {"word": "弟弟", "pinyin": "dì di"},
        {"word": "说话", "pinyin": "shuō huà"},
        {"word": "听话", "pinyin": "tīng huà"},
        {"word": "朋友", "pinyin": "péng you"},
        {"word": "高兴", "pinyin": "gāo xìng"},
        {"word": "快乐", "pinyin": "kuài lè"},
        {"word": "对面", "pinyin": "duì miàn"},
        {"word": "前面", "pinyin": "qián miàn"},
        {"word": "后面", "pinyin": "hòu miàn"},
        {"word": "里面", "pinyin": "lǐ miàn"},
        {"word": "外面", "pinyin": "wài miàn"},
        {"word": "古诗", "pinyin": "gǔ shī"},
        {"word": "写字", "pinyin": "xiě zì"},
        {"word": "生字", "pinyin": "shēng zì"},
        {"word": "学生", "pinyin": "xué shēng"},
        {"word": "同学", "pinyin": "tóng xué"},
        {"word": "老师", "pinyin": "lǎo shī"},
        {"word": "看见", "pinyin": "kàn jiàn"},
        {"word": "听见", "pinyin": "tīng jiàn"},
        {"word": "笑声", "pinyin": "xiào shēng"},
        {"word": "国王", "pinyin": "guó wáng"},
        {"word": "王子", "pinyin": "wáng zǐ"},
        {"word": "找到", "pinyin": "zhǎo dào"},
        {"word": "到处", "pinyin": "dào chù"},
        {"word": "过去", "pinyin": "guò qù"},
        {"word": "这里", "pinyin": "zhè lǐ"},
        {"word": "那里", "pinyin": "nà lǐ"},
        {"word": "为什么", "pinyin": "wèi shén me"},
        {"word": "什么", "pinyin": "shén me"},
        {"word": "时间", "pinyin": "shí jiān"},
        {"word": "许多", "pinyin": "xǔ duō"},
        {"word": "认真", "pinyin": "rèn zhēn"},
        {"word": "干净", "pinyin": "gān jìng"},
        {"word": "午后", "pinyin": "wǔ hòu"},
        {"word": "节日", "pinyin": "jié rì"},
        {"word": "叶子", "pinyin": "yè zi"},
        {"word": "种花", "pinyin": "zhòng huā"},
        {"word": "发现", "pinyin": "fā xiàn"},
        {"word": "成长", "pinyin": "chéng zhǎng"},
        {"word": "动物", "pinyin": "dòng wù"},
        {"word": "太阳", "pinyin": "tài yáng"},
        {"word": "月光", "pinyin": "yuè guāng"},
        {"word": "阳光", "pinyin": "yáng guāng"},
        {"word": "天空", "pinyin": "tiān kōng"},
        {"word": "河水", "pinyin": "hé shuǐ"},
        {"word": "听写", "pinyin": "tīng xiě"},
        {"word": "吃饭", "pinyin": "chī fàn"},
        {"word": "不行", "pinyin": "bù xíng"},
        {"word": "走路", "pinyin": "zǒu lù"},
    ],

    "二年级上": [
        {"word": "身体", "pinyin": "shēn tǐ"},
        {"word": "植物", "pinyin": "zhí wù"},
        {"word": "城市", "pinyin": "chéng shì"},
        {"word": "花园", "pinyin": "huā yuán"},
        {"word": "石桥", "pinyin": "shí qiáo"},
        {"word": "队旗", "pinyin": "duì qí"},
        {"word": "铜号", "pinyin": "tóng hào"},
        {"word": "红旗", "pinyin": "hóng qí"},
        {"word": "欢笑", "pinyin": "huān xiào"},
        {"word": "秋天", "pinyin": "qiū tiān"},
        {"word": "气候", "pinyin": "qì hòu"},
        {"word": "树叶", "pinyin": "shù yè"},
        {"word": "知识", "pinyin": "zhī shi"},
        {"word": "丰收", "pinyin": "fēng shōu"},
        {"word": "壮丽", "pinyin": "zhuàng lì"},
        {"word": "波浪", "pinyin": "bō làng"},
        {"word": "灯光", "pinyin": "dēng guāng"},
        {"word": "作业", "pinyin": "zuò yè"},
        {"word": "劳动", "pinyin": "láo dòng"},
        {"word": "才能", "pinyin": "cái néng"},
        {"word": "办法", "pinyin": "bàn fǎ"},
        {"word": "合作", "pinyin": "hé zuò"},
        {"word": "已经", "pinyin": "yǐ jīng"},
        {"word": "坐井观天", "pinyin": "zuò jǐng guān tiān"},
        {"word": "回答", "pinyin": "huí dá"},
        {"word": "井沿", "pinyin": "jǐng yán"},
        {"word": "口渴", "pinyin": "kǒu kě"},
        {"word": "办法", "pinyin": "bàn fǎ"},
        {"word": "每天", "pinyin": "měi tiān"},
        {"word": "其中", "pinyin": "qí zhōng"},
        {"word": "别人", "pinyin": "bié rén"},
        {"word": "到处", "pinyin": "dào chù"},
        {"word": "那些", "pinyin": "nà xiē"},
        {"word": "都是", "pinyin": "dōu shì"},
        {"word": "看着", "pinyin": "kàn zhe"},
        {"word": "高兴", "pinyin": "gāo xìng"},
        {"word": "可以", "pinyin": "kě yǐ"},
        {"word": "孩子", "pinyin": "hái zi"},
        {"word": "穿衣", "pinyin": "chuān yī"},
        {"word": "快乐", "pinyin": "kuài lè"},
        {"word": "朋友", "pinyin": "péng you"},
        {"word": "午饭", "pinyin": "wǔ fàn"},
        {"word": "汽车", "pinyin": "qì chē"},
        {"word": "公园", "pinyin": "gōng yuán"},
        {"word": "课文", "pinyin": "kè wén"},
        {"word": "图画", "pinyin": "tú huà"},
        {"word": "自己", "pinyin": "zì jǐ"},
    ],

    "二年级下": [
        {"word": "古诗", "pinyin": "gǔ shī"},
        {"word": "村庄", "pinyin": "cūn zhuāng"},
        {"word": "河边", "pinyin": "hé biān"},
        {"word": "碧绿", "pinyin": "bì lǜ"},
        {"word": "化妆", "pinyin": "huà zhuāng"},
        {"word": "柳树", "pinyin": "liǔ shù"},
        {"word": "桃花", "pinyin": "táo huā"},
        {"word": "邮局", "pinyin": "yóu jú"},
        {"word": "温暖", "pinyin": "wēn nuǎn"},
        {"word": "注意", "pinyin": "zhù yì"},
        {"word": "团结", "pinyin": "tuán jié"},
        {"word": "补充", "pinyin": "bǔ chōng"},
        {"word": "雷雨", "pinyin": "léi yǔ"},
        {"word": "乌云", "pinyin": "wū yún"},
        {"word": "黑色", "pinyin": "hēi sè"},
        {"word": "压力", "pinyin": "yā lì"},
        {"word": "彩虹", "pinyin": "cǎi hóng"},
        {"word": "太阳", "pinyin": "tài yáng"},
        {"word": "道理", "pinyin": "dào lǐ"},
        {"word": "年纪", "pinyin": "nián jì"},
        {"word": "决定", "pinyin": "jué dìng"},
        {"word": "商量", "pinyin": "shāng liang"},
        {"word": "工厂", "pinyin": "gōng chǎng"},
        {"word": "愿意", "pinyin": "yuàn yì"},
        {"word": "问题", "pinyin": "wèn tí"},
        {"word": "最后", "pinyin": "zuì hòu"},
        {"word": "故事", "pinyin": "gù shi"},
        {"word": "变化", "pinyin": "biàn huà"},
        {"word": "祖国", "pinyin": "zǔ guó"},
        {"word": "世界", "pinyin": "shì jiè"},
        {"word": "容易", "pinyin": "róng yì"},
        {"word": "困难", "pinyin": "kùn nan"},
        {"word": "满意", "pinyin": "mǎn yì"},
        {"word": "应该", "pinyin": "yīng gāi"},
        {"word": "如果", "pinyin": "rú guǒ"},
        {"word": "甜蜜", "pinyin": "tián mì"},
        {"word": "蜜蜂", "pinyin": "mì fēng"},
        {"word": "蜘蛛", "pinyin": "zhī zhū"},
        {"word": "青蛙", "pinyin": "qīng wā"},
        {"word": "眼睛", "pinyin": "yǎn jing"},
        {"word": "教室", "pinyin": "jiào shì"},
        {"word": "图书", "pinyin": "tú shū"},
    ],

    "三年级上": [
        {"word": "早晨", "pinyin": "zǎo chén"},
        {"word": "绒球", "pinyin": "róng qiú"},
        {"word": "服装", "pinyin": "fú zhuāng"},
        {"word": "鲜艳", "pinyin": "xiān yàn"},
        {"word": "打扮", "pinyin": "dǎ ban"},
        {"word": "安静", "pinyin": "ān jìng"},
        {"word": "朗读", "pinyin": "lǎng dú"},
        {"word": "粗壮", "pinyin": "cū zhuàng"},
        {"word": "凤凰", "pinyin": "fèng huáng"},
        {"word": "蝴蝶", "pinyin": "hú dié"},
        {"word": "孔雀", "pinyin": "kǒng què"},
        {"word": "舞蹈", "pinyin": "wǔ dǎo"},
        {"word": "寒冷", "pinyin": "hán lěng"},
        {"word": "离开", "pinyin": "lí kāi"},
        {"word": "丰富", "pinyin": "fēng fù"},
        {"word": "勤劳", "pinyin": "qín láo"},
        {"word": "观察", "pinyin": "guān chá"},
        {"word": "美丽", "pinyin": "měi lì"},
        {"word": "表面", "pinyin": "biǎo miàn"},
        {"word": "奇妙", "pinyin": "qí miào"},
        {"word": "迟到", "pinyin": "chí dào"},
        {"word": "准备", "pinyin": "zhǔn bèi"},
        {"word": "旅行", "pinyin": "lǚ xíng"},
        {"word": "拼命", "pinyin": "pīn mìng"},
        {"word": "摇头", "pinyin": "yáo tóu"},
        {"word": "追赶", "pinyin": "zhuī gǎn"},
        {"word": "方向", "pinyin": "fāng xiàng"},
        {"word": "幸福", "pinyin": "xìng fú"},
        {"word": "礼物", "pinyin": "lǐ wù"},
        {"word": "精彩", "pinyin": "jīng cǎi"},
        {"word": "感动", "pinyin": "gǎn dòng"},
        {"word": "愿望", "pinyin": "yuàn wàng"},
        {"word": "成功", "pinyin": "chéng gōng"},
        {"word": "汇合", "pinyin": "huì hé"},
        {"word": "拥抱", "pinyin": "yōng bào"},
        {"word": "奔跑", "pinyin": "bēn pǎo"},
        {"word": "阳光", "pinyin": "yáng guāng"},
        {"word": "温暖", "pinyin": "wēn nuǎn"},
        {"word": "举办", "pinyin": "jǔ bàn"},
        {"word": "匆忙", "pinyin": "cōng máng"},
    ],

    "三年级下": [
        {"word": "燕子", "pinyin": "yàn zi"},
        {"word": "聚拢", "pinyin": "jù lǒng"},
        {"word": "增添", "pinyin": "zēng tiān"},
        {"word": "偶尔", "pinyin": "ǒu ěr"},
        {"word": "映衬", "pinyin": "yìng chèn"},
        {"word": "荷花", "pinyin": "hé huā"},
        {"word": "莲蓬", "pinyin": "lián peng"},
        {"word": "饱胀", "pinyin": "bǎo zhàng"},
        {"word": "仿佛", "pinyin": "fǎng fú"},
        {"word": "位置", "pinyin": "wèi zhi"},
        {"word": "保存", "pinyin": "bǎo cún"},
        {"word": "完整", "pinyin": "wán zhěng"},
        {"word": "欧洲", "pinyin": "ōu zhōu"},
        {"word": "经验", "pinyin": "jīng yàn"},
        {"word": "修建", "pinyin": "xiū jiàn"},
        {"word": "创举", "pinyin": "chuàng jǔ"},
        {"word": "智慧", "pinyin": "zhì huì"},
        {"word": "赵县", "pinyin": "zhào xiàn"},
        {"word": "设计", "pinyin": "shè jì"},
        {"word": "节省", "pinyin": "jié shěng"},
        {"word": "坚固", "pinyin": "jiān gù"},
        {"word": "宝贵", "pinyin": "bǎo guì"},
        {"word": "鼓励", "pinyin": "gǔ lì"},
        {"word": "普通", "pinyin": "pǔ tōng"},
        {"word": "危险", "pinyin": "wēi xiǎn"},
        {"word": "顺利", "pinyin": "shùn lì"},
        {"word": "附近", "pinyin": "fù jìn"},
        {"word": "讨论", "pinyin": "tǎo lùn"},
        {"word": "研究", "pinyin": "yán jiū"},
        {"word": "麻烦", "pinyin": "má fan"},
        {"word": "骄傲", "pinyin": "jiāo ào"},
        {"word": "谦虚", "pinyin": "qiān xū"},
        {"word": "恼怒", "pinyin": "nǎo nù"},
        {"word": "朴素", "pinyin": "pǔ sù"},
        {"word": "价值", "pinyin": "jià zhí"},
        {"word": "忍受", "pinyin": "rěn shòu"},
        {"word": "吵闹", "pinyin": "chǎo nào"},
        {"word": "提醒", "pinyin": "tí xǐng"},
        {"word": "建议", "pinyin": "jiàn yì"},
        {"word": "负责", "pinyin": "fù zé"},
    ],

    "四年级上": [
        {"word": "潮水", "pinyin": "cháo shuǐ"},
        {"word": "观潮", "pinyin": "guān cháo"},
        {"word": "据说", "pinyin": "jù shuō"},
        {"word": "宽阔", "pinyin": "kuān kuò"},
        {"word": "笼罩", "pinyin": "lǒng zhào"},
        {"word": "薄雾", "pinyin": "bó wù"},
        {"word": "沸腾", "pinyin": "fèi téng"},
        {"word": "横贯", "pinyin": "héng guàn"},
        {"word": "恢复", "pinyin": "huī fù"},
        {"word": "灿烂", "pinyin": "càn làn"},
        {"word": "规律", "pinyin": "guī lǜ"},
        {"word": "均匀", "pinyin": "jūn yún"},
        {"word": "空隙", "pinyin": "kòng xì"},
        {"word": "叶柄", "pinyin": "yè bǐng"},
        {"word": "触角", "pinyin": "chù jiǎo"},
        {"word": "痕迹", "pinyin": "hén jì"},
        {"word": "逐渐", "pinyin": "zhú jiàn"},
        {"word": "住宅", "pinyin": "zhù zhái"},
        {"word": "隐蔽", "pinyin": "yǐn bì"},
        {"word": "隧道", "pinyin": "suì dào"},
        {"word": "骤然", "pinyin": "zhòu rán"},
        {"word": "搜索", "pinyin": "sōu suǒ"},
        {"word": "倾斜", "pinyin": "qīng xié"},
        {"word": "平坦", "pinyin": "píng tǎn"},
        {"word": "和谐", "pinyin": "hé xié"},
        {"word": "催促", "pinyin": "cuī cù"},
        {"word": "威武", "pinyin": "wēi wǔ"},
        {"word": "神秘", "pinyin": "shén mì"},
        {"word": "推荐", "pinyin": "tuī jiàn"},
        {"word": "屈服", "pinyin": "qū fú"},
        {"word": "呻吟", "pinyin": "shēn yín"},
        {"word": "疲劳", "pinyin": "pí láo"},
        {"word": "慰问", "pinyin": "wèi wèn"},
        {"word": "刚强", "pinyin": "gāng qiáng"},
        {"word": "牺牲", "pinyin": "xī shēng"},
        {"word": "崇高", "pinyin": "chóng gāo"},
        {"word": "豪迈", "pinyin": "háo mài"},
        {"word": "振奋", "pinyin": "zhèn fèn"},
        {"word": "胜利", "pinyin": "shèng lì"},
        {"word": "茂盛", "pinyin": "mào shèng"},
    ],

    "四年级下": [
        # 识字表 - 第1课
        {"word": "杂", "pinyin": "zá"},
        {"word": "篱", "pinyin": "lí"},
        {"word": "徐", "pinyin": "xú"},
        {"word": "疏", "pinyin": "shū"},
        {"word": "锄", "pinyin": "chú"},
        {"word": "剥", "pinyin": "bō"},
        # 识字表 - 第2课
        {"word": "构", "pinyin": "gòu"},
        {"word": "冠", "pinyin": "guān"},
        {"word": "朴", "pinyin": "pǔ"},
        {"word": "素", "pinyin": "sù"},
        {"word": "率", "pinyin": "shuài"},
        {"word": "倘", "pinyin": "tǎng"},
        {"word": "附", "pinyin": "fù"},
        {"word": "捣", "pinyin": "dǎo"},
        {"word": "绘", "pinyin": "huì"},
        {"word": "谐", "pinyin": "xié"},
        # 识字表 - 第3课
        {"word": "慰", "pinyin": "wèi"},
        {"word": "藉", "pinyin": "jiè"},
        {"word": "卜", "pinyin": "bǔ"},
        # 识字表 - 第4课
        {"word": "绮", "pinyin": "qǐ"},
        {"word": "和", "pinyin": "hè"},
        {"word": "谈", "pinyin": "tán"},
        # 识字表 - 第5课
        {"word": "琥", "pinyin": "hǔ"},
        {"word": "珀", "pinyin": "pò"},
        {"word": "翁", "pinyin": "wēng"},
        {"word": "脂", "pinyin": "zhī"},
        {"word": "拭", "pinyin": "shì"},
        {"word": "渗", "pinyin": "shèn"},
        {"word": "俯", "pinyin": "fǔ"},
        {"word": "扎", "pinyin": "zhá"},
        {"word": "番", "pinyin": "fān"},
        {"word": "埋", "pinyin": "mái"},
        {"word": "澎", "pinyin": "péng"},
        {"word": "湃", "pinyin": "pài"},
        # 识字表 - 第6课
        {"word": "钝", "pinyin": "dùn"},
        {"word": "描", "pinyin": "miáo"},
        {"word": "隧", "pinyin": "suì"},
        {"word": "衍", "pinyin": "yǎn"},
        {"word": "吨", "pinyin": "dūn"},
        {"word": "颅", "pinyin": "lú"},
        {"word": "膨", "pinyin": "péng"},
        {"word": "捷", "pinyin": "jié"},
        {"word": "辟", "pinyin": "pì"},
        {"word": "薪", "pinyin": "xīn"},
        # 识字表 - 第7课
        {"word": "乒", "pinyin": "pīng"},
        {"word": "乓", "pinyin": "pāng"},
        {"word": "拥", "pinyin": "yōng"},
        {"word": "菌", "pinyin": "jūn"},
        {"word": "臭", "pinyin": "chòu"},
        {"word": "蔬", "pinyin": "shū"},
        {"word": "碳", "pinyin": "tàn"},
        {"word": "癌", "pinyin": "ái"},
        {"word": "症", "pinyin": "zhèng"},
        {"word": "疾", "pinyin": "jí"},
        {"word": "灶", "pinyin": "zào"},
        # 识字表 - 第8课
        {"word": "鹏", "pinyin": "péng"},
        {"word": "揽", "pinyin": "lǎn"},
        {"word": "驱", "pinyin": "qū"},
        {"word": "践", "pinyin": "jiàn"},
        {"word": "着", "pinyin": "zhuó"},
        {"word": "党", "pinyin": "dǎng"},
        {"word": "施", "pinyin": "shī"},
        {"word": "懈", "pinyin": "xiè"},
        {"word": "宛", "pinyin": "wǎn"},
        {"word": "碑", "pinyin": "bēi"},
        # 识字表 - 语文园地(第1-8课)
        {"word": "宾", "pinyin": "bīn"},
        {"word": "吉", "pinyin": "jí"},
        {"word": "咸", "pinyin": "xián"},
        {"word": "兆", "pinyin": "zhào"},
        {"word": "廷", "pinyin": "tíng"},
        {"word": "予", "pinyin": "yǔ"},
        {"word": "肿", "pinyin": "zhǒng"},
        {"word": "阶", "pinyin": "jiē"},
        {"word": "趾", "pinyin": "zhǐ"},
        {"word": "逻", "pinyin": "luó"},
        {"word": "政", "pinyin": "zhèng"},
        {"word": "浏", "pinyin": "liú"},
        # 识字表 - 第9课
        {"word": "漫", "pinyin": "màn"},
        {"word": "涛", "pinyin": "tāo"},
        # 识字表 - 第10课
        {"word": "挤", "pinyin": "jǐ"},
        {"word": "叉", "pinyin": "chā"},
        # 识字表 - 第11课
        {"word": "绣", "pinyin": "xiù"},
        {"word": "潇", "pinyin": "xiāo"},
        {"word": "绞", "pinyin": "jiǎo"},
        {"word": "膝", "pinyin": "xī"},
        {"word": "朦", "pinyin": "méng"},
        {"word": "胧", "pinyin": "lóng"},
        {"word": "晖", "pinyin": "huī"},
        {"word": "徜", "pinyin": "cháng"},
        {"word": "徉", "pinyin": "yáng"},
        # 识字表 - 第12课
        {"word": "炫", "pinyin": "xuàn"},
        {"word": "垢", "pinyin": "gòu"},
        {"word": "怯", "pinyin": "qiè"},
        {"word": "曝", "pinyin": "pù"},
        {"word": "赤", "pinyin": "chì"},
        {"word": "携", "pinyin": "xié"},
        {"word": "涉", "pinyin": "shè"},
        {"word": "晕", "pinyin": "yùn"},
        # 识字表 - 语文园地(第11-12课)
        {"word": "屈", "pinyin": "qū"},
        {"word": "渊", "pinyin": "yuān"},
        {"word": "孟", "pinyin": "mèng"},
        {"word": "甫", "pinyin": "fǔ"},
        {"word": "韩", "pinyin": "hán"},
        {"word": "愈", "pinyin": "yù"},
        {"word": "禹", "pinyin": "yǔ"},
        {"word": "锡", "pinyin": "xī"},
        {"word": "仲", "pinyin": "zhòng"},
        {"word": "龚", "pinyin": "gōng"},
        # 识字表 - 第13课
        {"word": "忧", "pinyin": "yōu"},
        {"word": "虑", "pinyin": "lǜ"},
        {"word": "职", "pinyin": "zhí"},
        {"word": "屏", "pinyin": "bǐng"},
        {"word": "蹭", "pinyin": "cèng"},
        {"word": "稿", "pinyin": "gǎo"},
        {"word": "腔", "pinyin": "qiāng"},
        {"word": "殉", "pinyin": "xùn"},
        {"word": "折", "pinyin": "shé"},
        # 识字表 - 第14课
        {"word": "疙", "pinyin": "gē"},
        {"word": "瘩", "pinyin": "da"},
        {"word": "侮", "pinyin": "wǔ"},
        {"word": "恶", "pinyin": "wù"},
        {"word": "毒", "pinyin": "dú"},
        {"word": "韦", "pinyin": "wéi"},
        {"word": "咏", "pinyin": "yǒng"},
        {"word": "伏", "pinyin": "fú"},
        {"word": "哼", "pinyin": "hēng"},
        {"word": "嗓", "pinyin": "sǎng"},
        {"word": "凄", "pinyin": "qī"},
        # 识字表 - 第15课
        {"word": "调", "pinyin": "diào"},
        {"word": "看", "pinyin": "kān"},
        {"word": "罄", "pinyin": "qìng"},
        {"word": "吭", "pinyin": "kēng"},
        {"word": "吠", "pinyin": "fèi"},
        {"word": "促", "pinyin": "cù"},
        {"word": "颠", "pinyin": "diān"},
        {"word": "奢", "pinyin": "shē"},
        {"word": "侈", "pinyin": "chǐ"},
        {"word": "苟", "pinyin": "gǒu"},
        {"word": "侍", "pinyin": "shì"},
        {"word": "窥", "pinyin": "kuī"},
        {"word": "伺", "pinyin": "sì"},
        {"word": "供", "pinyin": "gòng"},
        # 识字表 - 语文园地(第13-15课)
        {"word": "肝", "pinyin": "gān"},
        {"word": "秆", "pinyin": "gǎn"},
        {"word": "俏", "pinyin": "qiào"},
        {"word": "峭", "pinyin": "qiào"},
        {"word": "噪", "pinyin": "zào"},
        {"word": "浦", "pinyin": "pǔ"},
        {"word": "沧", "pinyin": "cāng"},
        {"word": "抡", "pinyin": "lún"},
        {"word": "沦", "pinyin": "lún"},
        {"word": "涣", "pinyin": "huàn"},
        {"word": "焕", "pinyin": "huàn"},
        {"word": "俊", "pinyin": "jùn"},
        {"word": "峻", "pinyin": "jùn"},
        # 识字表 - 第16课
        {"word": "扩", "pinyin": "kuò"},
        {"word": "荷", "pinyin": "hè"},
        {"word": "刹", "pinyin": "chà"},
        {"word": "镶", "pinyin": "xiāng"},
        # 识字表 - 第17课
        {"word": "浙", "pinyin": "zhè"},
        {"word": "簇", "pinyin": "cù"},
        {"word": "臀", "pinyin": "tún"},
        {"word": "漆", "pinyin": "qī"},
        {"word": "蜿", "pinyin": "wān"},
        {"word": "蜒", "pinyin": "yán"},
        # 识字表 - 第18课
        {"word": "恭", "pinyin": "gōng"},
        {"word": "勤", "pinyin": "qín"},
        {"word": "驾", "pinyin": "jià"},
        {"word": "卒", "pinyin": "zú"},
        # 识字表 - 第19课
        {"word": "晋", "pinyin": "jìn"},
        {"word": "絮", "pinyin": "xù"},
        {"word": "扭", "pinyin": "niǔ"},
        {"word": "姑", "pinyin": "gū"},
        {"word": "吧", "pinyin": "ba"},
        {"word": "塞", "pinyin": "sāi"},
        {"word": "鸣", "pinyin": "míng"},
        {"word": "哇", "pinyin": "wā"},
        {"word": "糠", "pinyin": "kāng"},
        {"word": "栓", "pinyin": "shuān"},
        {"word": "捆", "pinyin": "kǔn"},
        {"word": "绑", "pinyin": "bǎng"},
        {"word": "劫", "pinyin": "jié"},
        {"word": "毙", "pinyin": "bì"},
        {"word": "扒", "pinyin": "bā"},
        {"word": "尸", "pinyin": "shī"},
        # 识字表 - 第20课
        {"word": "徽", "pinyin": "huī"},
        {"word": "谜", "pinyin": "mí"},
        {"word": "唇", "pinyin": "chún"},
        {"word": "尚", "pinyin": "shàng"},
        {"word": "抖", "pinyin": "dǒu"},
        {"word": "偏", "pinyin": "piān"},
        {"word": "强", "pinyin": "qiáng"},
        {"word": "嘹", "pinyin": "liáo"},
        {"word": "呐", "pinyin": "nà"},
        {"word": "忍", "pinyin": "rěn"},
        {"word": "泪", "pinyin": "lèi"},
        {"word": "坑", "pinyin": "kēng"},
        {"word": "仪", "pinyin": "yí"},
        {"word": "蹬", "pinyin": "dēng"},
        {"word": "坊", "pinyin": "fáng"},
        # 识字表 - 第21课
        {"word": "搓", "pinyin": "cuō"},
        {"word": "葵", "pinyin": "kuí"},
        {"word": "祈", "pinyin": "qí"},
        {"word": "遗", "pinyin": "yí"},
        {"word": "憾", "pinyin": "hàn"},
        {"word": "污", "pinyin": "wū"},
        {"word": "屑", "pinyin": "xiè"},
        # 识字表 - 第22课
        {"word": "芙", "pinyin": "fú"},
        {"word": "蓉", "pinyin": "róng"},
        {"word": "洛", "pinyin": "luò"},
        {"word": "单", "pinyin": "chán"},
        {"word": "砚", "pinyin": "yàn"},
        {"word": "乾", "pinyin": "qián"},
        {"word": "坤", "pinyin": "kūn"},
        # 识字表 - 第23课
        {"word": "役", "pinyin": "yì"},
        {"word": "屡", "pinyin": "lǚ"},
        {"word": "启", "pinyin": "qǐ"},
        {"word": "摧", "pinyin": "cuī"},
        {"word": "雷", "pinyin": "léi"},
        {"word": "膛", "pinyin": "táng"},
        # 识字表 - 第24课
        {"word": "弥", "pinyin": "mí"},
        {"word": "脉", "pinyin": "mài"},
        {"word": "葬", "pinyin": "zàng"},
        {"word": "剖", "pinyin": "pōu"},
        {"word": "裸", "pinyin": "luǒ"},
        {"word": "泣", "pinyin": "qì"},
        {"word": "汹", "pinyin": "xiōng"},
        {"word": "维", "pinyin": "wéi"},
        {"word": "悍", "pinyin": "hàn"},
        {"word": "械", "pinyin": "xiè"},
        {"word": "岗", "pinyin": "gǎng"},
        {"word": "宰", "pinyin": "zǎi"},
        {"word": "遣", "pinyin": "qiǎn"},
        # 识字表 - 第25课
        {"word": "泰", "pinyin": "tài"},
        {"word": "杖", "pinyin": "zhàng"},
        {"word": "敞", "pinyin": "chǎng"},
        {"word": "拘", "pinyin": "jū"},
        {"word": "蕴", "pinyin": "yùn"},
        # 识字表 - 语文园地(第25课)
        {"word": "蔼", "pinyin": "ǎi"},
        {"word": "慷", "pinyin": "kāng"},
        {"word": "慨", "pinyin": "kǎi"},
        {"word": "贤", "pinyin": "xián"},
        {"word": "戚", "pinyin": "qī"},
        {"word": "惧", "pinyin": "jù"},
        {"word": "彬", "pinyin": "bīn"},
        {"word": "躁", "pinyin": "zào"},
        {"word": "焚", "pinyin": "fén"},
        # 识字表 - 第26课
        {"word": "妖", "pinyin": "yāo"},
        {"word": "矩", "pinyin": "jǔ"},
        {"word": "乖", "pinyin": "guāi"},
        {"word": "撵", "pinyin": "niǎn"},
        {"word": "丫", "pinyin": "yā"},
        {"word": "拽", "pinyin": "zhuài"},
        {"word": "冲", "pinyin": "chòng"},
        {"word": "瘦", "pinyin": "shòu"},
        # 识字表 - 第27课
        {"word": "硕", "pinyin": "shuò"},
        {"word": "允", "pinyin": "yǔn"},
        {"word": "砌", "pinyin": "qì"},
        {"word": "覆", "pinyin": "fù"},
        {"word": "啸", "pinyin": "xiào"},
        {"word": "缕", "pinyin": "lǚ"},
        {"word": "搂", "pinyin": "lǒu"},
        {"word": "颊", "pinyin": "jiá"},
        # 识字表 - 第28课
        {"word": "矢", "pinyin": "shǐ"},
        {"word": "殿", "pinyin": "diàn"},
        {"word": "抚", "pinyin": "fǔ"},
        {"word": "鲸", "pinyin": "jīng"},
        {"word": "呢", "pinyin": "ní"},
        {"word": "恰", "pinyin": "qià"},
        # 词语表 - 第2课
        {"word": "屋檐", "pinyin": "wū yán"},
        {"word": "构成", "pinyin": "gòu chéng"},
        {"word": "装饰", "pinyin": "zhuāng shì"},
        {"word": "顺序", "pinyin": "shùn xù"},
        {"word": "华丽", "pinyin": "huá lì"},
        {"word": "独特", "pinyin": "dú tè"},
        {"word": "照例", "pinyin": "zhào lì"},
        {"word": "率领", "pinyin": "shuài lǐng"},
        {"word": "踏步", "pinyin": "tà bù"},
        {"word": "倘若", "pinyin": "tǎng ruò"},
        {"word": "和谐", "pinyin": "hé xié"},
        {"word": "催眠曲", "pinyin": "cuī mián qǔ"},
        {"word": "甜蜜", "pinyin": "tián mì"},
        {"word": "梦乡", "pinyin": "mèng xiāng"},
        # 词语表 - 第3课
        {"word": "慰藉", "pinyin": "wèi jiè"},
        {"word": "扫荡", "pinyin": "sǎo dàng"},
        {"word": "威力", "pinyin": "wēi lì"},
        {"word": "锐利", "pinyin": "ruì lì"},
        {"word": "河滩", "pinyin": "hé tān"},
        {"word": "帐子", "pinyin": "zhàng zi"},
        {"word": "闪烁", "pinyin": "shǎn shuò"},
        {"word": "奇幻", "pinyin": "qí huàn"},
        {"word": "蝙蝠", "pinyin": "biān fú"},
        {"word": "霸气", "pinyin": "bà qì"},
        {"word": "猫头鹰", "pinyin": "māo tóu yīng"},
        {"word": "复杂", "pinyin": "fù zá"},
        # 词语表 - 第5课
        {"word": "怒吼", "pinyin": "nù hǒu"},
        {"word": "松脂", "pinyin": "sōng zhī"},
        {"word": "拂拭", "pinyin": "fú shì"},
        {"word": "灰尘", "pinyin": "huī chén"},
        {"word": "美餐", "pinyin": "měi cān"},
        {"word": "晌午", "pinyin": "shǎng wǔ"},
        {"word": "热辣辣", "pinyin": "rè là là"},
        {"word": "淹没", "pinyin": "yān mò"},
        {"word": "挣扎", "pinyin": "zhēng zhá"},
        {"word": "成千上万", "pinyin": "chéng qiān shàng wàn"},
        {"word": "冲刷", "pinyin": "chōng shuā"},
        {"word": "断绝", "pinyin": "duàn jué"},
        {"word": "推测", "pinyin": "tuī cè"},
        {"word": "详细", "pinyin": "xiáng xì"},
        {"word": "情形", "pinyin": "qíng xíng"},
        # 词语表 - 第6课
        {"word": "恐龙", "pinyin": "kǒng lóng"},
        {"word": "笨重", "pinyin": "bèn zhòng"},
        {"word": "迟钝", "pinyin": "chí dùn"},
        {"word": "鸽子", "pinyin": "gē zi"},
        {"word": "凌空", "pinyin": "líng kōng"},
        {"word": "根据", "pinyin": "gēn jù"},
        {"word": "末期", "pinyin": "mò qī"},
        {"word": "描绘", "pinyin": "miáo huì"},
        {"word": "隧道", "pinyin": "suì dào"},
        {"word": "地球", "pinyin": "dì qiú"},
        {"word": "形态", "pinyin": "xíng tài"},
        {"word": "膨大", "pinyin": "péng dà"},
        {"word": "前肢", "pinyin": "qián zhī"},
        {"word": "具备", "pinyin": "jù bèi"},
        {"word": "开辟", "pinyin": "kāi pì"},
        {"word": "脱离", "pinyin": "tuō lí"},
        # 词语表 - 第7课
        {"word": "纳米", "pinyin": "nà mǐ"},
        {"word": "无能为力", "pinyin": "wú néng wéi lì"},
        {"word": "拥有", "pinyin": "yōng yǒu"},
        {"word": "冰箱", "pinyin": "bīng xiāng"},
        {"word": "功能", "pinyin": "gōng néng"},
        {"word": "蔬菜", "pinyin": "shū cài"},
        {"word": "材料", "pinyin": "cái liào"},
        {"word": "钢铁", "pinyin": "gāng tiě"},
        {"word": "隐形", "pinyin": "yǐn xíng"},
        {"word": "健康", "pinyin": "jiàn kāng"},
        {"word": "细胞", "pinyin": "xì bāo"},
        {"word": "疾病", "pinyin": "jí bìng"},
        {"word": "预防", "pinyin": "yù fáng"},
        {"word": "病灶", "pinyin": "bìng zào"},
        {"word": "需要", "pinyin": "xū yào"},
        {"word": "深刻", "pinyin": "shēn kè"},
        # 词语表 - 第9课
        {"word": "繁星", "pinyin": "fán xīng"},
        {"word": "藤萝", "pinyin": "téng luó"},
        {"word": "波涛", "pinyin": "bō tāo"},
        # 词语表 - 第10课
        {"word": "墨绿", "pinyin": "mò lǜ"},
        {"word": "嫩绿", "pinyin": "nèn lǜ"},
        {"word": "集中", "pinyin": "jí zhōng"},
        {"word": "交叉", "pinyin": "jiāo chā"},
        {"word": "教练", "pinyin": "jiào liàn"},
        {"word": "指挥", "pinyin": "zhǐ huī"},
        {"word": "整齐", "pinyin": "zhěng qí"},
        {"word": "节拍", "pinyin": "jié pāi"},
        # 词语表 - 第11课
        {"word": "白桦", "pinyin": "bái huà"},
        {"word": "毛茸茸", "pinyin": "máo róng róng"},
        {"word": "潇洒", "pinyin": "xiāo sǎ"},
        {"word": "朦胧", "pinyin": "méng lóng"},
        {"word": "寂静", "pinyin": "jì jìng"},
        {"word": "朝霞", "pinyin": "zhāo xiá"},
        # 词语表 - 第13课
        {"word": "呼唤", "pinyin": "hū huàn"},
        {"word": "响动", "pinyin": "xiǎng dòng"},
        {"word": "尽职", "pinyin": "jìn zhí"},
        {"word": "屏息", "pinyin": "bǐng xī"},
        {"word": "稿纸", "pinyin": "gǎo zhǐ"},
        {"word": "梅花", "pinyin": "méi huā"},
        {"word": "解闷", "pinyin": "jiě mèn"},
        {"word": "勇猛", "pinyin": "yǒng měng"},
        {"word": "满月", "pinyin": "mǎn yuè"},
        {"word": "淘气", "pinyin": "táo qì"},
        # 词语表 - 第14课
        {"word": "讨厌", "pinyin": "tǎo yàn"},
        {"word": "理由", "pinyin": "lǐ yóu"},
        {"word": "心事", "pinyin": "xīn shì"},
        {"word": "反抗", "pinyin": "fǎn kàng"},
        {"word": "忠厚", "pinyin": "zhōng hòu"},
        {"word": "毒手", "pinyin": "dú shǒu"},
        {"word": "成绩", "pinyin": "chéng jì"},
        {"word": "警戒", "pinyin": "jǐng jiè"},
        {"word": "预备", "pinyin": "yù bèi"},
        {"word": "汤圆", "pinyin": "tāng yuán"},
        # 词语表 - 第15课
        {"word": "即将", "pinyin": "jí jiāng"},
        {"word": "姿态", "pinyin": "zī tài"},
        {"word": "高傲", "pinyin": "gāo ào"},
        {"word": "音调", "pinyin": "yīn diào"},
        {"word": "局促", "pinyin": "jú cù"},
        {"word": "京剧", "pinyin": "jīng jù"},
        {"word": "一丝不苟", "pinyin": "yī sī bù gǒu"},
        {"word": "譬如", "pinyin": "pì rú"},
        {"word": "侍候", "pinyin": "shì hòu"},
        {"word": "饭馆", "pinyin": "fàn guǎn"},
        {"word": "附近", "pinyin": "fù jìn"},
        {"word": "脾气", "pinyin": "pí qì"},
        {"word": "敏捷", "pinyin": "mǐn jié"},
        {"word": "空空如也", "pinyin": "kōng kōng rú yě"},
        {"word": "昂首", "pinyin": "áng shǒu"},
        {"word": "供养", "pinyin": "gòng yǎng"},
        # 词语表 - 第16课
        {"word": "清静", "pinyin": "qīng jìng"},
        {"word": "扩大", "pinyin": "kuò dà"},
        {"word": "范围", "pinyin": "fàn wéi"},
        {"word": "努力", "pinyin": "nǔ lì"},
        {"word": "刹那", "pinyin": "chà nà"},
        {"word": "夺目", "pinyin": "duó mù"},
        {"word": "分辨", "pinyin": "fēn biàn"},
        {"word": "灿烂", "pinyin": "càn làn"},
        {"word": "不仅", "pinyin": "bù jǐn"},
        # 词语表 - 第17课
        {"word": "杜鹃", "pinyin": "dù juān"},
        {"word": "气势", "pinyin": "qì shì"},
        {"word": "聚集", "pinyin": "jù jí"},
        {"word": "拥挤", "pinyin": "yōng jǐ"},
        {"word": "心情", "pinyin": "xīn qíng"},
        {"word": "脚跟", "pinyin": "jiǎo gēn"},
        {"word": "移动", "pinyin": "yí dòng"},
        {"word": "昏暗", "pinyin": "hūn àn"},
        {"word": "挤压", "pinyin": "jǐ yā"},
        {"word": "额角", "pinyin": "é jiǎo"},
        {"word": "登陆", "pinyin": "dēng lù"},
        {"word": "宽广", "pinyin": "kuān guǎng"},
        {"word": "石钟乳", "pinyin": "shí zhōng rǔ"},
        {"word": "石笋", "pinyin": "shí sǔn"},
        {"word": "观赏", "pinyin": "guān shǎng"},
        # 词语表 - 第19课
        {"word": "芦花", "pinyin": "lú huā"},
        {"word": "发愣", "pinyin": "fā lèng"},
        {"word": "铅笔", "pinyin": "qiān bǐ"},
        {"word": "摇晃", "pinyin": "yáo huàng"},
        {"word": "枪栓", "pinyin": "qiāng shuān"},
        {"word": "胳膊", "pinyin": "gē bo"},
        {"word": "劫难", "pinyin": "jié nàn"},
        {"word": "鬼脸", "pinyin": "guǐ liǎn"},
        {"word": "戒指", "pinyin": "jiè zhǐ"},
        {"word": "绸子", "pinyin": "chóu zi"},
        {"word": "敌人", "pinyin": "dí rén"},
        {"word": "尸首", "pinyin": "shī shǒu"},
        {"word": "防备", "pinyin": "fáng bèi"},
        {"word": "慌忙", "pinyin": "huāng máng"},
        # 词语表 - 第23课
        {"word": "战场", "pinyin": "zhàn chǎng"},
        {"word": "持续", "pinyin": "chí xù"},
        {"word": "命令", "pinyin": "mìng lìng"},
        {"word": "占领", "pinyin": "zhàn lǐng"},
        {"word": "射击", "pinyin": "shè jī"},
        {"word": "突击", "pinyin": "tū jī"},
        {"word": "枪弹", "pinyin": "qiāng dàn"},
        {"word": "愤怒", "pinyin": "fèn nù"},
        {"word": "注视", "pinyin": "zhù shì"},
        {"word": "光荣", "pinyin": "guāng róng"},
        {"word": "艰巨", "pinyin": "jiān jù"},
        {"word": "消息", "pinyin": "xiāo xi"},
        {"word": "炮弹", "pinyin": "pào dàn"},
        {"word": "爆炸", "pinyin": "bào zhà"},
        {"word": "烈火", "pinyin": "liè huǒ"},
        {"word": "子弹", "pinyin": "zǐ dàn"},
        {"word": "不料", "pinyin": "bù liào"},
        {"word": "规定", "pinyin": "guī dìng"},
        {"word": "惊天动地", "pinyin": "jīng tiān dòng dì"},
        {"word": "消灭", "pinyin": "xiāo miè"},
        # 词语表 - 第24课
        {"word": "行驶", "pinyin": "xíng shǐ"},
        {"word": "凌晨", "pinyin": "líng chén"},
        {"word": "窟窿", "pinyin": "kū long"},
        {"word": "混乱", "pinyin": "hùn luàn"},
        {"word": "维持", "pinyin": "wéi chí"},
        {"word": "秩序", "pinyin": "zhì xù"},
        {"word": "岗位", "pinyin": "gǎng wèi"},
        {"word": "主宰", "pinyin": "zhǔ zǎi"},
        {"word": "调遣", "pinyin": "diào qiǎn"},
        {"word": "践行", "pinyin": "jiàn xíng"},
        # 词语表 - 第26课
        {"word": "介绍", "pinyin": "jiè shào"},
        {"word": "声明", "pinyin": "shēng míng"},
        {"word": "妖怪", "pinyin": "yāo guài"},
        {"word": "规矩", "pinyin": "guī ju"},
        {"word": "劈面", "pinyin": "pī miàn"},
        {"word": "幸福", "pinyin": "xìng fú"},
        {"word": "向日葵", "pinyin": "xiàng rì kuí"},
        # 词语表 - 第27课
        {"word": "柔嫩", "pinyin": "róu nèn"},
        {"word": "丰硕", "pinyin": "fēng shuò"},
        {"word": "允许", "pinyin": "yǔn xǔ"},
        {"word": "禁止", "pinyin": "jìn zhǐ"},
        {"word": "踪迹", "pinyin": "zōng jì"},
        {"word": "呼啸", "pinyin": "hū xiào"},
        {"word": "始终", "pinyin": "shǐ zhōng"},
        {"word": "吼叫", "pinyin": "hǒu jiào"},
        {"word": "自私", "pinyin": "zì sī"},
        {"word": "举动", "pinyin": "jǔ dòng"},
        {"word": "脸颊", "pinyin": "liǎn jiá"},
        {"word": "凶狠", "pinyin": "xiōng hěn"},
        {"word": "拆除", "pinyin": "chāi chú"},
    ],

    "五年级上": [
        {"word": "精巧", "pinyin": "jīng qiǎo"},
        {"word": "浸透", "pinyin": "jìn tòu"},
        {"word": "缝隙", "pinyin": "fèng xì"},
        {"word": "飘泊", "pinyin": "piāo bó"},
        {"word": "姿态", "pinyin": "zī tài"},
        {"word": "逊色", "pinyin": "xùn sè"},
        {"word": "疏忽", "pinyin": "shū hu"},
        {"word": "教训", "pinyin": "jiào xun"},
        {"word": "目前", "pinyin": "mù qián"},
        {"word": "嫌弃", "pinyin": "xián qì"},
        {"word": "糟糕", "pinyin": "zāo gāo"},
        {"word": "配合", "pinyin": "pèi hé"},
        {"word": "眺望", "pinyin": "tiào wàng"},
        {"word": "爱慕", "pinyin": "ài mù"},
        {"word": "衷心", "pinyin": "zhōng xīn"},
        {"word": "报酬", "pinyin": "bào chou"},
        {"word": "抵御", "pinyin": "dǐ yù"},
        {"word": "侵略", "pinyin": "qīn lüè"},
        {"word": "崎岖", "pinyin": "qí qū"},
        {"word": "沉着", "pinyin": "chén zhuó"},
        {"word": "壮烈", "pinyin": "zhuàng liè"},
        {"word": "豪迈", "pinyin": "háo mài"},
        {"word": "坚强", "pinyin": "jiān qiáng"},
        {"word": "胸膛", "pinyin": "xiōng táng"},
        {"word": "沉重", "pinyin": "chén zhòng"},
        {"word": "严肃", "pinyin": "yán sù"},
        {"word": "踌躇", "pinyin": "chóu chú"},
        {"word": "嘱咐", "pinyin": "zhǔ fù"},
        {"word": "搀扶", "pinyin": "chān fú"},
        {"word": "安顿", "pinyin": "ān dùn"},
        {"word": "瞅见", "pinyin": "chǒu jiàn"},
        {"word": "魁梧", "pinyin": "kuí wu"},
        {"word": "苦刑", "pinyin": "kǔ xíng"},
        {"word": "绞刑", "pinyin": "jiǎo xíng"},
        {"word": "残暴", "pinyin": "cán bào"},
        {"word": "匪徒", "pinyin": "fěi tú"},
        {"word": "转移", "pinyin": "zhuǎn yí"},
        {"word": "书籍", "pinyin": "shū jí"},
        {"word": "遮挡", "pinyin": "zhē dǎng"},
        {"word": "繁忙", "pinyin": "fán máng"},
    ],

    "五年级下": [
        {"word": "牧童", "pinyin": "mù tóng"},
        {"word": "蓑衣", "pinyin": "suō yī"},
        {"word": "毡帽", "pinyin": "zhān mào"},
        {"word": "卸货", "pinyin": "xiè huò"},
        {"word": "咀嚼", "pinyin": "jǔ jué"},
        {"word": "妨碍", "pinyin": "fáng ài"},
        {"word": "侮辱", "pinyin": "wǔ rǔ"},
        {"word": "矛盾", "pinyin": "máo dùn"},
        {"word": "招待", "pinyin": "zhāo dài"},
        {"word": "安居乐业", "pinyin": "ān jū lè yè"},
        {"word": "求饶", "pinyin": "qiú ráo"},
        {"word": "神机妙算", "pinyin": "shén jī miào suàn"},
        {"word": "嫉妒", "pinyin": "jí dù"},
        {"word": "推却", "pinyin": "tuī què"},
        {"word": "迟延", "pinyin": "chí yán"},
        {"word": "探听", "pinyin": "tàn tīng"},
        {"word": "私自", "pinyin": "sī zì"},
        {"word": "调度", "pinyin": "diào dù"},
        {"word": "水寨", "pinyin": "shuǐ zhài"},
        {"word": "呐喊", "pinyin": "nà hǎn"},
        {"word": "丞相", "pinyin": "chéng xiàng"},
        {"word": "都督", "pinyin": "dū du"},
        {"word": "委托", "pinyin": "wěi tuō"},
        {"word": "照常", "pinyin": "zhào cháng"},
        {"word": "胸有成竹", "pinyin": "xiōng yǒu chéng zhú"},
        {"word": "手忙脚乱", "pinyin": "shǒu máng jiǎo luàn"},
        {"word": "惊慌失措", "pinyin": "jīng huāng shī cuò"},
        {"word": "兴高采烈", "pinyin": "xìng gāo cǎi liè"},
        {"word": "垂头丧气", "pinyin": "chuí tóu sàng qì"},
        {"word": "目瞪口呆", "pinyin": "mù dèng kǒu dāi"},
        {"word": "心旷神怡", "pinyin": "xīn kuàng shén yí"},
        {"word": "情不自禁", "pinyin": "qíng bù zì jīn"},
        {"word": "活蹦乱跳", "pinyin": "huó bèng luàn tiào"},
        {"word": "惊天动地", "pinyin": "jīng tiān dòng dì"},
        {"word": "奄奄一息", "pinyin": "yǎn yǎn yī xī"},
        {"word": "遗体", "pinyin": "yí tǐ"},
        {"word": "丰碑", "pinyin": "fēng bēi"},
        {"word": "喷射", "pinyin": "pēn shè"},
        {"word": "维护", "pinyin": "wéi hù"},
        {"word": "素质", "pinyin": "sù zhì"},
    ],

    "六年级上": [
        {"word": "瀑布", "pinyin": "pù bù"},
        {"word": "陡峭", "pinyin": "dǒu qiào"},
        {"word": "津津乐道", "pinyin": "jīn jīn lè dào"},
        {"word": "别出心裁", "pinyin": "bié chū xīn cái"},
        {"word": "技术", "pinyin": "jì shù"},
        {"word": "吞没", "pinyin": "tūn mò"},
        {"word": "刚劲", "pinyin": "gāng jìng"},
        {"word": "拘束", "pinyin": "jū shù"},
        {"word": "蒙眬", "pinyin": "méng lóng"},
        {"word": "凄凉", "pinyin": "qī liáng"},
        {"word": "恍惚", "pinyin": "huǎng hū"},
        {"word": "消瘦", "pinyin": "xiāo shòu"},
        {"word": "抱歉", "pinyin": "bào qiàn"},
        {"word": "魁梧", "pinyin": "kuí wu"},
        {"word": "苗条", "pinyin": "miáo tiao"},
        {"word": "威严", "pinyin": "wēi yán"},
        {"word": "勉励", "pinyin": "miǎn lì"},
        {"word": "疙瘩", "pinyin": "gē da"},
        {"word": "纠纷", "pinyin": "jiū fēn"},
        {"word": "协商", "pinyin": "xié shāng"},
        {"word": "沮丧", "pinyin": "jǔ sàng"},
        {"word": "要挟", "pinyin": "yāo xié"},
        {"word": "恳切", "pinyin": "kěn qiè"},
        {"word": "渺小", "pinyin": "miǎo xiǎo"},
        {"word": "慷慨", "pinyin": "kāng kǎi"},
        {"word": "贡献", "pinyin": "gòng xiàn"},
        {"word": "璀璨", "pinyin": "cuǐ càn"},
        {"word": "资源", "pinyin": "zī yuán"},
        {"word": "枯竭", "pinyin": "kū jié"},
        {"word": "滥用", "pinyin": "làn yòng"},
        {"word": "威胁", "pinyin": "wēi xié"},
        {"word": "目睹", "pinyin": "mù dǔ"},
        {"word": "指望", "pinyin": "zhǐ wàng"},
        {"word": "领悟", "pinyin": "lǐng wù"},
        {"word": "咆哮", "pinyin": "páo xiào"},
        {"word": "嗓子", "pinyin": "sǎng zi"},
        {"word": "搀扶", "pinyin": "chān fú"},
        {"word": "祭奠", "pinyin": "jì diàn"},
        {"word": "呻吟", "pinyin": "shēn yín"},
        {"word": "废墟", "pinyin": "fèi xū"},
    ],

    "六年级下": [
        {"word": "腊月", "pinyin": "là yuè"},
        {"word": "展览", "pinyin": "zhǎn lǎn"},
        {"word": "蜜饯", "pinyin": "mì jiàn"},
        {"word": "搅拌", "pinyin": "jiǎo bàn"},
        {"word": "浓稠", "pinyin": "nóng chóu"},
        {"word": "熬粥", "pinyin": "áo zhōu"},
        {"word": "褐色", "pinyin": "hè sè"},
        {"word": "爆竹", "pinyin": "bào zhú"},
        {"word": "风筝", "pinyin": "fēng zheng"},
        {"word": "截然", "pinyin": "jié rán"},
        {"word": "燃放", "pinyin": "rán fàng"},
        {"word": "小贩", "pinyin": "xiǎo fàn"},
        {"word": "彼此", "pinyin": "bǐ cǐ"},
        {"word": "摆摊", "pinyin": "bǎi tān"},
        {"word": "棚架", "pinyin": "péng jià"},
        {"word": "挽回", "pinyin": "wǎn huí"},
        {"word": "恐惧", "pinyin": "kǒng jù"},
        {"word": "残暴", "pinyin": "cán bào"},
        {"word": "惧怕", "pinyin": "jù pà"},
        {"word": "哀思", "pinyin": "āi sī"},
        {"word": "领袖", "pinyin": "lǐng xiù"},
        {"word": "革命", "pinyin": "gé mìng"},
        {"word": "解放", "pinyin": "jiě fàng"},
        {"word": "严峻", "pinyin": "yán jùn"},
        {"word": "机智", "pinyin": "jī zhì"},
        {"word": "不屈", "pinyin": "bù qū"},
        {"word": "赤诚", "pinyin": "chì chéng"},
        {"word": "缺乏", "pinyin": "quē fá"},
        {"word": "粗犷", "pinyin": "cū guǎng"},
        {"word": "抽象", "pinyin": "chōu xiàng"},
        {"word": "境界", "pinyin": "jìng jiè"},
        {"word": "栩栩如生", "pinyin": "xǔ xǔ rú shēng"},
        {"word": "翩翩起舞", "pinyin": "piān piān qǐ wǔ"},
        {"word": "画龙点睛", "pinyin": "huà lóng diǎn jīng"},
        {"word": "惟妙惟肖", "pinyin": "wéi miào wéi xiào"},
        {"word": "活灵活现", "pinyin": "huó líng huó xiàn"},
        {"word": "妙笔生花", "pinyin": "miào bǐ shēng huā"},
        {"word": "蓬勃", "pinyin": "péng bó"},
        {"word": "依依不舍", "pinyin": "yī yī bù shě"},
        {"word": "憧憬", "pinyin": "chōng jǐng"},
    ],
}
